### PR TITLE
Avoid using process.exit

### LINKED ISSUE #149: Output truncated in Node.js 6
In Node.js 6 the output is sometimes (seems to happen when there is more than a few lines in the output) truncated because the process is killed before process.stdout is flushed.

The fix for this is to stop using `process.exit()` and instead use `process.exitCode = `.

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #149

### CODE REVIEW

**Comment by LinusU** [comment]
ping @dylang, this is a blocker on Node.js 6

**Comment by LinusU** [comment]
I have been running this locally for a month now, it works great 👍

**Comment by lijunle** [comment]
@LinusU Glad to see you being a collaborator! Awesome! :sunglasses:

**Comment by LinusU** [comment]
Thank you! 😎

**Pull request merged**
