### PR TITLE
ES7 Migration 🚗, Modernization, Refactoring 🔨

### PR DESCRIPTION
**Pull request by amilajack**
**⚠️ Do not merge! Work in progress⚠️**

- [x] Upgrade babel presets
- [x] Migrate to `eslint-preset-airbnb-base`
- [x] Added flow support
- [x] Migrate from grunt -> npm scripts
- [x] Add jest support
- [x] E2E ESLint tests
- [ ] E2E Webpack tests
- [ ] E2E Babel tests
- [ ] E2E peerDependency tests
- [ ] E2E npm script and .bin validation tests

### CODE REVIEW

**Comment by LinusU** [comment]
Just a quick thought, since Node 0.x is end of life, would it be feasible to drop Babel altogether?

**Comment by amilajack** [comment]
node 4 doesn't support >= es6. We still need babel. Also we're using babel will be used for import/export statements and flow (in the future).

**Comment by LinusU** [comment]
I was thinking that it maybe would be easier to develop with `require` instead of having to use babel for that. I think that that is the only big thing not supported, but I might be wrong. Anyhow, just a thought :)

**Comment by amilajack** [comment]
http://node.green

The coverage of node 5 and 4 requires us to use babel :( There's still a significant number of users on node < 6.

**Pull request closed without merging**
