### PR TITLE
add typescript dependency

### PR DESCRIPTION
**Pull request by technicallyjosh**
Per `depcheck`, if you have TypeScript installed as a dependency, it works on TypeScript files.

This should resolve some issues such as:
* https://github.com/dylang/npm-check/issues/311
* https://github.com/dylang/npm-check/issues/339
* https://github.com/dylang/npm-check/issues/313

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, so I thought that it would pick up the local dependency on TypeScript 🤔 

The only problem with this is that it will always use the TypeScript version that _we_ define, instead of using the same as the package that is being checked...

Not sure if that is a big deal though 🤔

**Comment by technicallyjosh** [comment]
> The only problem with this is that it will always use the TypeScript version that we define, instead of using the same as the package that is being checked...

It's up to you guys if you want to include it by default. I figured I'd make it a _non issue_ since it's a dependency that requires it to be installed. Perhaps adding docs might be just as good of a fix to let people know to do an `npm i -g npm-check typescript` if they want TypeScript files included. 🤷‍♂

**Comment by Artoria2e5** [comment]
It can be made a "peer" dependency or put in optionalDependencies.

**Comment by newlukai** [comment]
I find it quite difficult to get information on how to let npm-check know that my project uses TypeScript. I hope that globally installing TypeScript is not the only way.
I'm working on several projects using different TypeScript versions and it's not feasible for me to install TypeScript globally. Additionally I don't want to bring TypeScript to production, so I usually include TypeScript as devDependency.
And it seems that doesn't work for npm-check.

**Comment by newlukai** [comment]
I noticed that my issues regarding TypeScript were fixed after updating the depcheck dependency. Thus I added a [PR](https://github.com/dylang/npm-check/pull/385).
But I also noticed that the latest commit was to downgrade depcheck in order to restore compatibility with older Node versions.
So are we in a quandary now?

**Comment by technicallyjosh** [comment]
I don't use the lib anymore and this is super stale. 😅

**Pull request closed without merging**
