### PR TITLE
Added travis ci support for node 6

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by LinusU** [comment]
I think that it's a good idea to remove `5` since Travis inly gives us (I think, I might be wrong) 4 parallel builds. Also, that version is no longer supported and most people are either using 4 or using/are in the process of migrating to 6. Furthermore, if it works on 4 and on 6, it probably works on 5 as well.

Sounds good?

**Comment by amilajack** [comment]
Sounds good. Sorry for late reply

**Comment by amilajack** [comment]
I added travis ci support for mac os. Is that fine?

**Comment by LinusU** [comment]
Hmm Travis are usually quite slow on starting OS X tests which can be frustrating at times, but on the other hand it's quite good to have OS X coverage. Let's try it, and if it's too slow we'll revert 👍

**Comment by amilajack** [comment]
@LinusU good idea

**Pull request merged**
