### PR TITLE
Fix resolution of NODE_PATH

### LINKED ISSUE #263: Fails to init if NODE_PATH is set and has more than one entry
Today I started running into:
```
$ npm-check -sug
process.env.NODE_PATH does not exist. Please check the environment variables.
For more detail, add `--debug` to the command
```

But I do have `NODE_PATH` set, what's going on?
```
$ env | grep NODE_PATH
NODE_PATH=/usr/local/lib/node_modules:/Users/crccheck/local/node
```

It turns out it also checks to make sure `NODE_PATH` exists on the filesystem

https://github.com/dylang/npm-check/blob/1ac1eb3455eb02d2a4265d640a7842ead207f9d4/lib/state/init.js#L17

But it according to the [Node docs](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders), `NODE_PATH` can be "a colon-delimited list of absolute paths". So the current logic should split all the paths and check them, maybe with a `.reduce`.

----

I don't know why this just started today. I've had that in my environment for years. The only change I did was to upgrade to Node 8 LTS from Node 8.8. I fixed the problem by removing `NODE_PATH` from my dotfiles because I wasn't even using it but others may run into this.

### PR DESCRIPTION
**Pull request by LinusU**
fixes #263

### CODE REVIEW

**Comment by crccheck** [comment]
I tried it on my system and got:
```
$ NODE_PATH=/usr/local/lib/node_modules:/tmp/iliketurtles npm-check -sug
warning: Using the first of multiple paths specified in NODE_PATH
The global path you are searching is: /usr/local/lib/node_modules
❤️  Your modules look amazing. Keep up the great work. ❤️

$ NODE_PATH=/tmp/iliketurtles:/usr/local/lib/node_modules npm-check -sug
warning: Using the first of multiple paths specified in NODE_PATH
Path "/tmp/iliketurtles" does not exist. Please check the NODE_PATH environment variable.
For more detail, add `--debug` to the command
```

**Comment by LinusU** [comment]
For some reason Travis is super slow, but I'll merge anyways since I want to get this out before going to bed...

**Comment by LinusU** [comment]
Published as 5.5.1

**Comment by junjiangao** [comment]
is not work well in windows

**Comment by LinusU** [comment]
@junjiangao what error do you get? I'd be happy to try and get it working...

**Comment by crccheck** [comment]
I wonder if `NODE_PATH` in Windows is `;` even though npm says: "a colon-delimited list of absolute paths", because Windows uses semicolons `;` for its path separators. I looked into it, and Node has `path.delimiter` https://nodejs.org/api/path.html#path_path_delimiter

But that would have been broken even in the first implementation for the same reason

**Comment by LinusU** [comment]
Fix: #266

**Comment by Berkmann18** [comment]
Not sure if this issue was fixed but it seems that npm-check doesn't consider the path specified by `$NODE_PATH` which makes it ignore packages listed by `npm ls -g`.

**Pull request merged**
