### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/assemble/grunt-readme | https://github.com/jonschlinkert/grunt-readme 
https://github.com/rumpl/depcheck | https://github.com/depcheck/depcheck 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://img.shields.io/npm/dm/npm-check.svg | https://img.shields.io/npm/dm/npm-check.svg 
http://img.shields.io/travis/dylang/npm-check.svg | https://img.shields.io/travis/dylang/npm-check.svg 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://opower.com | https://opower.com/ 
https://www.npmjs.com/onsite | https://www.npmjs.com/enterprise 
https://www.npmjs.org/doc/cli/npm-outdated.html | https://docs.npmjs.com/cli/outdated 
https://www.npmjs.org/package/npm-check | https://www.npmjs.com/package/npm-check

### CODE REVIEW

**Comment by dylang** [comment]
All of the old urls forward to the new locations, so there won't be any errors, but this is great. 

This project uses a readme generator so we'll need to move the changes over to the templates.

**Comment by ReadmeCritic** [comment]
Ah bummer..
Are all the links in one file??

**Comment by dylang** [comment]
Hi @ReadmeCritic, they are in [several files](https://github.com/dylang/npm-check/tree/master/templates/readme), but that's fine, I wouldn't expect the bot to know that.

I've been thinking about going back to a single README because I get PR's from non-bots (humans) to the README.md file too because it's not clear it's generated from a set of templates.

**Comment by ReadmeCritic** [comment]
Maybe a contributing or pull request template might help https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by amilajack** [comment]
Please resolve conflicts on this branch

**Comment by ReadmeCritic** [comment]
opening another one 😅

**Pull request closed without merging**
