### PR TITLE
Update depcheck to latest

### PR DESCRIPTION
**Pull request by rumpl**
There were a great deal of fixes and new features lately

### CODE REVIEW

**Comment by gilboagl** [comment]
@rumpl  is someone going create a new release for this?

**Comment by rumpl** [comment]
I have no idea and no write permissions on this repo 😅

@dylang ?

**Comment by mkarpusiewicz** [comment]
There is a couple of PR for updating dependencies, I would stick to one, like https://github.com/dylang/npm-check/pull/368 and try to get it merged.

**Comment by vasanthdeveloper** [comment]
Why isn't this merged yet? @dylang Please update dependencies to resolve security issues :)

**Comment by icebob** [comment]
When will be merged it?

**Comment by LinusU** [comment]
fixed in #368

**Pull request closed without merging**
