### PR TITLE
Fixed README.md link

### PR DESCRIPTION
**Pull request by simlu**
Fixed link and used relative instead of absolute path. This should probably be done for all links...

### CODE REVIEW

**Comment by LinusU** [comment]
> This should probably be done for all links...

Would you mind? 😊

**Comment by OiYouYeahYou** [comment]
Just had a look myself, I can't seem to find any other dead links? Might be useful to merge after 6 months of inactivity?

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Released in v5.7.1

**Pull request merged**
