### PR TITLE
Ignore jspm_packages

### PR DESCRIPTION
**Pull request by Hypercubed**
Fix for #139 , ignore jspm_packages directory.

### CODE REVIEW

**Comment by LinusU** [comment]
This looks good to me, I'll give @dylang a day or two to complain, otherwise I'll merge this 👍

**Comment by lijunle** [comment]
@LinusU You should treat it as [a feature](https://github.com/depcheck/depcheck/issues/155) for depcheck. :smiley:

**Comment by amilajack** [comment]
@LinusU What is the status of this?

**Comment by LinusU** [comment]
Let's merge it!

**Pull request merged**
