### PR TITLE
Fixing CI for Node 4

### PR DESCRIPTION
**Pull request by mansona**
I noticed that CI was broken on one of my other PRs https://github.com/dylang/npm-check/pull/323 because apparently Yarn doesn't support Node 4 

I'm not trying to open a can of worms with the whole "npm vs Yarn" debate, all I know is that CI is currently broken and this PR fixes the issue 👍 

I also added testing in Node 8 and 10 for good measure 🎉

### CODE REVIEW

**Comment by LinusU** [comment]
I'm okay with switching to npm, what do you think @dylang? ☺️

**Comment by lorenzleutgeb** [comment]
I just proposed a similar change in #351. I didn't touch lockfiles, however. @mansona maybe you could update your PR by also including Node 12 which has since been released and is now the most current LTS.

**Comment by mansona** [comment]
@lorenzleutgeb I have updated the PR as requested. I haven't removed the old node versions that are EOL right now (4 and 6) because that would require a major version bump of npm-check

If this passes we can at least get it merged and then decide to drop node 4 and node 6 support later 👍

**Comment by lorenzleutgeb** [comment]
Not sure if removing a testing environment from build automation constitutes a breaking change. No interface to the outside world is being changed. But I get your point that it would be more diligent to test with Node 4 as well :)

Now let's hope some maintainers are around...

**Comment by mansona** [comment]
I am part of one of the Ember core teams and we have a policy that when you stop testing a particular version you're dropping support for that version. Essentially if anyone adds a small change (like arrow functions) you won't notice that it breaks the build in Node 4 because you're not testing it anymore 😄 It's why I wanted to fix CI in the first place so that it was still a clear **intent** of versions that you want to support 👍

**Comment by mhatvan** [comment]
Agreeing with @mansona here, it is very common that JS libraries bump up a major version when they drop support for an older node version.

**Comment by LinusU** [comment]
Thanks!

**Pull request merged**
