### PR TITLE
Add option to save exact versions

### LINKED ISSUE #90: Support --save-exact
In our project we always save exact versions (without the carrot `^`). This is done using the `npm install` option for `--save-exact`

### PR DESCRIPTION
**Pull request by pgilad**
Fixes #90

### CODE REVIEW

**Comment by pgilad** [comment]
@dylang any updates?

**Comment by dylang** [comment]
@pgilad Thanks for doing this! I'm reviewing it now. Sorry for lack communication on my part.

**Comment by dylang** [comment]
Looks great, merging it in now! Thanks again!

**Comment by pgilad** [comment]
Thanks for the project! Cheers

**Pull request merged**
