### PR TITLE
Updated deps

### PR DESCRIPTION
**Pull request by amilajack**
**Please do not merge, as this is a work in progress 👷**

### CODE REVIEW

**Comment by amilajack** [comment]
@LinusU Just to confirm, the tests test if the module works correctly? [This](https://github.com/dylang/npm-check/blob/master/package.json#L11) made me feel like it wasn't. I expected some unit testing.

**Comment by LinusU** [comment]
Hmm, I'm quite new to this project, but it seems like there should be some kind of unit testing... Shouldn't be to hard to make some, maybe with [`nock`](https://npmjs.com/nock)...

**Comment by amilajack** [comment]
How about an end-to-end test? Say we have some kind of test repo and we run npm-check on it. We then collect the results of npm-check, store those results, and then run all our tests against those initial results.

**Comment by amilajack** [comment]
@LinusU would be great if you could prerelease this. I would recommend using [np](https://github.com/sindresorhus/np) to do this.

**Pull request closed without merging**
